/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VArrowBack: typeof import('./src/components/Icons/VArrowBack.vue')['default']
    VButton: typeof import('./src/components/Button/VButton.vue')['default']
    VDisLike: typeof import('./src/components/Icons/VDisLike.vue')['default']
    VFaceBook: typeof import('./src/components/Icons/VFaceBook.vue')['default']
    VFooter: typeof import('./src/components/Footer/VFooter.vue')['default']
    VHeader: typeof import('./src/components/Header/VHeader.vue')['default']
    VImage: typeof import('./src/components/Image/VImage.vue')['default']
    VInput: typeof import('./src/components/Input/VInput.vue')['default']
    VInstagram: typeof import('./src/components/Icons/VInstagram.vue')['default']
    VLanguage: typeof import('./src/components/Icons/VLanguage.vue')['default']
    VLike: typeof import('./src/components/Icons/VLike.vue')['default']
    VLogo: typeof import('./src/components/Icons/VLogo.vue')['default']
    VMenu: typeof import('./src/components/Icons/VMenu.vue')['default']
    VPlay: typeof import('./src/components/Icons/VPlay.vue')['default']
    VSearch: typeof import('./src/components/Icons/VSearch.vue')['default']
    VTwitter: typeof import('./src/components/Icons/VTwitter.vue')['default']
    VUser: typeof import('./src/components/Icons/VUser.vue')['default']
    VYoutube: typeof import('./src/components/Icons/VYoutube.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
